build:
  tags:
    - linux
  script:
    # build deps
    - cd 3rdparty
    - ./submodules.sh
    - cd ..

    # create environment
    - python3 -m venv env
    - source env/bin/activate
    # get packages
    - pip install numpy
    - pip install cython		
    - pip install -r requirements.txt

    # agrossuite
    - ln -s ~/.local/lib/python3.7/site-packages/agrossuite env/lib/python3.7/site-packages/agrossuite

    # tests
    - cd artap/tests
    - pytest --disable-warnings --durations=0 -v
